osx_image: xcode7.3

cache:
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.cache

before_install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.5.5/git-lfs-darwin-amd64-1.5.5.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull

install:
- nvm install 7
- npm install

script:
- npm run build-mac

branches:
  only:
    - master
