os:
  - osx

osx_image: xcode7.3

language: c

cache:
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.cache

install:
- nvm install 7
- npm install

script:
- npm run build-mac

branches:
  only:
    - master
